# Generated by Django 4.2.8 on 2023-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.FloatField(verbose_name="fruits-vegetables-nuts_100g"),
                ),
            ],
        ),
    ]
