# Generated by Django 4.2.8 on 2023-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "categories",
                    models.CharField(max_length=30, verbose_name="categories_en"),
                ),
                (
                    "countries",
                    models.CharField(max_length=30, verbose_name="countries_en"),
                ),
                ("labels", models.CharField(max_length=30, verbose_name="labels_en")),
                (
                    "ingredients",
                    models.CharField(max_length=30, verbose_name="ingredients_text"),
                ),
                (
                    "main_category",
                    models.CharField(max_length=30, verbose_name="main_category_en"),
                ),
                ("energy", models.FloatField(verbose_name="energy_100")),
                ("image", models.ImageField(upload_to="", verbose_name="image_url")),
                ("saturated_fat", models.FloatField(verbose_name="saturated-fat_100g")),
                ("sugar", models.FloatField(verbose_name="sugars_100g")),
                ("protein", models.FloatField(verbose_name="proteins_100g")),
                ("salt", models.FloatField(verbose_name="salt_100g")),
                (
                    "fruit_veg",
                    models.FloatField(verbose_name="fruits-vegetables-nuts_100g"),
                ),
            ],
            options={
                "verbose_name": "Eco",
                "verbose_name_plural": "Ecos",
                "db_table": "eco",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="file",
        ),
    ]
