# Generated by Django 4.2.8 on 2023-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_eco_delete_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="eco",
            name="excel_file",
            field=models.FileField(blank=True, null=True, upload_to="excel_files/"),
        ),
    ]
