# Generated by Django 4.2.8 on 2023-12-26 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_eco_excel_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eco",
            name="excel_file",
        ),
    ]
