# Generated by Django 4.2.8 on 2023-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_rename_countries_eco_categories_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eco",
            old_name="categories",
            new_name="countries_en",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="fruit_veg",
            new_name="energy_100g",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="energy",
            new_name="fiber_100g",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="protein",
            new_name="fruits_vegetables_nuts_100g",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="image",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="ingredients",
            new_name="ingredients_text",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="main_category",
            new_name="main_category_en",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="salt",
            new_name="proteins_100g",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="saturated_fat",
            new_name="salt_100g",
        ),
        migrations.RenameField(
            model_name="eco",
            old_name="sugar",
            new_name="saturated_fat_100g",
        ),
        migrations.AddField(
            model_name="eco",
            name="sugars_100g",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
