# Generated by Django 4.2.8 on 2023-12-28 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_rename_categories_eco_countries_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eco",
            old_name="labels",
            new_name="labels_en",
        ),
    ]
