# Generated by Django 4.2.8 on 2023-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_rename_labels_eco_labels_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="eco",
            name="packaging_en",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
