# Generated by Django 4.2.8 on 2024-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_eco_packaging_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="eco",
            name="score_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
