# Generated by Django 4.2.8 on 2024-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_eco_score_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="eco",
            name="EcoScore",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eco",
            name="NutriScore",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eco",
            name="NutriScore_letter",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="eco",
            name="brands",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="eco",
            name="eco_Grade",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="eco",
            name="serving_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eco",
            name="stores",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
