# Generated by Django 4.2.8 on 2024-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_eco_ecoscore_eco_nutriscore_eco_nutriscore_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eco",
            name="serving_size",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
